services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
    env_file:
      - ./frontend/.env
    networks:
      - mynetwork
  
  backend:
    build: ./backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    
networks:
  mynetwork:
    driver: bridge